### ISSUE TITLE
Improve MySQL sync speed

### ISSUE THREAD

**Issue by gregharvey** [codeenigma/ansible-deploy#285]
We should separate the unzipping action from the MySQL import because `bzcat` of a zip file piped to `mysql` is really slow!

**Comment by galooph** [comment]
@tymofiisobchenko has been working on this – see https://github.com/codeenigma/ce-deploy/pull/337 and https://github.com/codeenigma/ce-deploy/pull/338

**Comment by tymofiisobchenko** [comment]
#291  Splitting tasks into separate ones gave a small advantage (which is also difficult to measure, because the database involved in the comparison is constantly growing). At least the load has noticeably reduced, before these changes the server was almost unresponsive during the sync process. The main advantage was in the moving from bzip2 to gzip (archive size differs insignificantly, but the speed in times).
